### ISSUE TITLE
Data Export

### ISSUE THREAD

**Issue by gavar** [victorstanciu/dbv#71]
Would be very handy to also export table data into separate files as it is done with schemes. Recently I was trying to find software where you can back-up & restore database schemes from separate files (1 file per table  scheme, 1 file per table scheme) and could not find anything. DBV is very close to this, I think it can become very popular for users who like to version control files/database via GIT/SVN/HG (especially me).

**Comment by victorstanciu** [comment]
Sorry, database data backups are not within the project's scope. I am only interested in versioning the database structure.
