### ISSUE TITLE
I find an bug in pdo.php

### ISSUE THREAD

**Issue by lukelau** [victorstanciu/dbv#79]
when run selected revisions , i could not know error message about sql error, because  function query don't throw any exception!

should change
public function query($sql)
{
     return $this->_connection->query($sql);
}

to 
   public function query($sql)
    {	
		try{
			return $this->_connection->query($sql);
		}
		catch(Exception $e) {
			throw new DBV_Exception($e->getMessage(), (int)$e->getCode());
		}
	}

**Comment by victorstanciu** [comment]
Fixed: https://github.com/victorstanciu/dbv/commit/cbbf24cad9204b2b49575b851d45efce0dfceefd
