### ISSUE TITLE
dbv on Mac OS X 10.9.x

### ISSUE THREAD

**Issue by september28** [victorstanciu/dbv#81]
Hi there,

I didn't have too much luck installing the php extension dependencies for dbv (gettext and intl) on Mac OS X 10.9.5.

Gettext seems to install OK as per this tutorial - http://idev.ge/installing-gettext-on-mac-osx-10-9
I followed the same process for the intl.so which seemed to go ok, however when trying to access dbv/index.php in browser the following error appears:
Fatal error: Call to undefined function bind_textdomain_codeset() in /Path/to/dbv/config.php on line 54

There seems to be little about this issue on the web, however some suggestions that the Mac OS X version of the internationalisation library doesn't have this method.

My workaround so far is to change line 54 of config.php to:
if (function_exists('bind_textdomain_codeset')) bind_textdomain_codeset(DEFAULT_DOMAIN, DEFAULT_ENCODING);

Any other thoughts?

Thanks

Dan

**Comment by worldoffaizan** [comment]
Just include "gettext.so" extension in your "php.ini" file with complete path like this:
extension=/usr/lib/php/extensions/no-debug-non-zts-20100525/gettext.so

NOTE: Update the path accordingly.

**Comment by victorstanciu** [comment]
The gettext dependency is no longer mandatory since https://github.com/victorstanciu/dbv/pull/66
