### ISSUE TITLE
Error in applying revisions

### ISSUE THREAD

**Issue by gtmsingh** [victorstanciu/dbv#82]
I tried to apply a revision but it fails without any error popping up and when I tried to use the "Save file" utility, I got this as an error. I cannot understand what is wrong in it.
![dbv error](https://cloud.githubusercontent.com/assets/8234335/5626313/d2599bd0-95af-11e4-88e3-c6680325658b.png)

PS. I have run the same by copy-paste in the space provided by phpmyadmin and it worked absolutely fine.

**Comment by victorstanciu** [comment]
Spaces in file names are not supported. See: https://github.com/victorstanciu/dbv/blob/master/DBV.php#L187
