### ISSUE TITLE
Expired certificate on https://dbv.vizuina.com/

### ISSUE THREAD

**Issue by OndraM** [victorstanciu/dbv#99]
Hi,
the certificate for https://dbv.vizuina.com/ is expired.

> dbv.vizuina.com uses an invalid security certificate. 
> The certificate expired on 12.4.2017 12:26. The current time is 23.4.2017 22:12. 
> Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by victorstanciu** [comment]
Fixed, thanls!
